#!/bin/sh
#
# A(d)sorber v#@version@# crontab file
# Updates the hosts file once a week.
#
# For more information: https://github.com/stablestud/adsorber
# Or send me an email: <adsorber@stablestud.org>
#
# adsorber install --cron:
# By default this file is going to be copied into /etc/cron.weekly/ if not
# other specified.

#@/some/path/adsorber update@#
